### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by utaal** [buildo/cashflow#7]
`npm install` hangs after installing semantic and you need to press enter for it to continue. Also, interactive installation prevents automated builds.
Additionally, `gulp build` hangs when run in `web/` after completion.

**Comment by gabro** [comment]
`npm install` before last command?

**Comment by utaal** [comment]
are they even serious?

**Comment by gabro** [comment]
Also: 2d24e3e107be1cdb455966e7122a949272e99955

**Comment by utaal** [comment]
`cd semantic; gulp build` results in

```
module.js:338
    throw err;
          ^
Error: Cannot find module './project/config'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/utaal/Src/buildo/cashflow/web/semantic/tasks/config/user.js:14:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
