### ISSUE TITLE
Stuck in "Caricamento..."

### ISSUE THREAD

**Issue by utaal** [buildo/cashflow#8]
Recent log lines:

```
TypeError: Cannot read property 'userId' of null
    at Object.getUserByToken (/srv/cashflow-api/src/utils.js:17:66)
    at GeneratorFunctionPrototype.next (native)
    at Object.next (/srv/cashflow-api/node_modules/koa/node_modules/co/index.js:74:21)
    at /srv/cashflow-api/node_modules/koa/node_modules/co/index.js:93:18
    at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/collection/query.js:147:5
    at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:738:35
    at Cursor.close (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:959:5)
    at Cursor.nextObject (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:738:17)
    at commandHandler (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:713:14)
    at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/db.js:1806:9
    at Server.Base._callHandler (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    at MongoReply.parseBody (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:418:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

  TypeError: Cannot read property 'userId' of null
      at Object.getUserByToken (/srv/cashflow-api/src/utils.js:17:66)
      at GeneratorFunctionPrototype.next (native)
      at Object.next (/srv/cashflow-api/node_modules/koa/node_modules/co/index.js:74:21)
      at /srv/cashflow-api/node_modules/koa/node_modules/co/index.js:93:18
      at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/collection/query.js:147:5
      at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:738:35
      at Cursor.close (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:959:5)
      at Cursor.nextObject (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:738:17)
      at commandHandler (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/cursor.js:713:14)
      at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/db.js:1806:9
      at Server.Base._callHandler (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
      at /srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
      at MongoReply.parseBody (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
      at null.<anonymous> (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
      at emit (events.js:107:17)
      at null.<anonymous> (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
      at emit (events.js:110:17)
      at Socket.<anonymous> (/srv/cashflow-api/node_modules/co-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:418:22)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
```

**Comment by utaal** [comment]
Had to delete leftover `{type: 'manual'}` rows from db.
